# Generated by Django 5.0.1 on 2024-02-07 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='año',
            new_name='anio',
        ),
    ]
