# Generated by Django 5.0.1 on 2024-02-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0004_alter_cliente_options_alter_editorial_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libro', models.CharField(max_length=50)),
                ('cliente', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
    ]
